### ISSUE TITLE
Argument 'show' is ignored

### ISSUE THREAD

**Issue by orestesgaolin** [lesnitsky/fps_widget#2]
1. Set `show` to false
2. FPSWidget is still shown

**Comment by mantresh-pvt** [comment]
I fixed that issue and added a pull request to merge with the master branch.
[Forked Repository](https://github.com/mantreshkhurana/fps_widget)

**Comment by lesnitsky** [comment]
Closed in 0018fb389d8af86c6e3a6a2f7078f687c30380d9
